CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  risk_level VARCHAR(20) NOT NULL,
  cash_balance NUMERIC(14, 2) NOT NULL DEFAULT 10000.00
);

CREATE TABLE IF NOT EXISTS portfolio (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  ticker VARCHAR(20) NOT NULL,
  quantity INTEGER NOT NULL,
  avg_price NUMERIC(14, 4) NOT NULL DEFAULT 0
);
